---
title: "Poster 1.5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(ggthemes)
library(viridis)

raw <- read_csv("RKI_COVID19(1).csv") %>%
  mutate(Meldedatum = as_date(Meldedatum))
meldestand <- max(raw$Datenstand)
selection <- raw %>% 
  filter(str_detect(Landkreis, c("Aachen","Köln", "Berlin Mitte")))
## Recoding selection$Landkreis
selection$Landkreis <- fct_recode(selection$Landkreis,
               "Köln" = "SK Köln",
               "Städteregion Aachen" = "StadtRegion Aachen",
               "Berlin Mitte" = "SK Berlin Mitte")

```

```{r}
selection %>%   
  group_by(Landkreis, Meldedatum) %>% 
  summarise(AnzahlFall = sum(AnzahlFall)) %>% 
  ggplot() +
  aes(x = Meldedatum, y = AnzahlFall, fill = Landkreis) +
  geom_col() + 
  facet_wrap(~Landkreis) +
  labs(x = "Meldedatum", y = "Anzahl gemeldeter Fälle",
         title = "Vergleich der Neuinfektionen zwischen Berlin, Aachen und Köln",
         subtitle = "Alle Landkreise zeigen einen Rückgang der Infektionen.
Der Mindestabstand sollte jedoch weiterhin eingehalten werden, um einen erneuten Anstieg zu verhindern.",
         caption = paste("Daten vom RKI, Meldestand:", meldestand)) +
  scale_x_date(date_labels = "%d.%m.", date_breaks = "1 month") +
  scale_fill_manual(values = c("#67A8FF", "#FF8C80", "#9CB33E")) +
  theme_tufte() +
  theme(
    panel.background = element_rect(fill = "transparent"), # bg of the panel
    plot.background = element_rect(fill = "transparent", color = NA), # bg of the plot
    panel.grid.major = element_blank(), # get rid of major grid
    panel.grid.minor = element_blank(), # get rid of minor grid
    legend.background = element_rect(fill = "transparent"), # get rid of legend bg
    legend.box.background = element_rect(fill = "transparent"),# get rid of legend panel bg
    axis.title.x=element_blank(), #x-Achsen-Beschriftung entfernen
    legend.position = c(0.14,0.74)
  )
ggsave("plot.png", width = 7, height = 4, dpi = 600, bg = "transparent")


```

